In [ ]:
import numpy as np

In [ ]:
# 1d array
n1 = np.array([3,4,5,6])

In [ ]:
print(n1)

[3 4 5 6]


In [ ]:
#2d array
n2 = np.array([[3,4,5,6],[7,8,9,1]])
print(n2)

[[3 4 5 6]
 [7 8 9 1]]


In [ ]:
#zero filled 2d array
n3 = np.zeros([3,5],dtype='int32')
print(n3)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
#array filled with ones
n4 = np.ones([2,3,4], dtype='int32')
print(n4)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [ ]:
#array with range of numbers
n5 = np.arange(0,10,2) # a range
print(n5)

[0 2 4 6 8]


In [ ]:
n6 = np.arange(10)
print(n6)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
n7 = np.arange(-5,10,5)
print(n7)

[-5  0  5]


In [ ]:
n8 = np.arange(-5,30,5)
print(n8)

[-5  0  5 10 15 20 25]


In [15]:
n9 = np.full([2,5],99)
print(n9)

[[99 99 99 99 99]
 [99 99 99 99 99]]


## **ACCESSING ARRAY**

**Accessing 1 dimensional array**

In [16]:
print(n1)

[3 4 5 6]


In [17]:
print(n1[0])

3


In [19]:
print(n1[-1])   #Accessing last element in an array
print(n1[-2])   #Accessing second last element in an array

6
5


**Accesing 2 dimensional array**

In [20]:
print(n2)

[[3 4 5 6]
 [7 8 9 1]]


[[3 4 5 6]  - 1st row

 [7 8 9 1]] - 2nd row

In [21]:
print(n2[1,0])

7


In [23]:
print(n2[0,0])
print(n2[0,1])
print(n2[0,2])
print(n2[0,3])

3
4
5
6


In [24]:
print(n2[0,:])

[3 4 5 6]


In [25]:
print(n2[1,:])

[7 8 9 1]


In [26]:
print(n2[1,2])

9


if **:** is at last means ->  accessing **row**

if **:** is at front means -> accessing **column**

In [27]:
print(n2)

[[3 4 5 6]
 [7 8 9 1]]


In [28]:
print(n2[:,3])

[6 1]


**Accessing 3 dimensional array**

In [29]:
print(n4)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [30]:
#updating a  3d array
# first specify array no, then row no, column no
n4[1,1,2] = 10
print(n4)

[[[ 1  1  1  1]
  [ 1  1  1  1]
  [ 1  1  1  1]]

 [[ 1  1  1  1]
  [ 1  1 10  1]
  [ 1  1  1  1]]]


## **SIZE AND SHAPE**

In [31]:
print(n4.ndim)

3


In [32]:
print(n4.shape)
# 2 block or matrices
# 3 rows
# 4 columns

(2, 3, 4)


In [33]:
print(n4.size)

24


In [34]:
print(n4.dtype)

int32


In [35]:
print(n4.itemsize) # how many size need for storing each element


4


In [36]:
print(n4.nbytes) #24*4 = 96

96


# **SORTING**

In [37]:
#1D Array
n10 = np.array([2,4,5,9,8,1])
np.sort(n10)

array([1, 2, 4, 5, 8, 9])

In [38]:
#2D Array
n11 = np.array([[3,8,1],[9,1,3]])
np.sort(n11)

array([[1, 3, 8],
       [1, 3, 9]])

In [39]:
print(n11)

[[3 8 1]
 [9 1 3]]


In [41]:
#sort column wise.....
np.sort(n11,axis=0)

array([[3, 1, 1],
       [9, 8, 3]])

# **Reshaping and Array Conversions**

In [45]:
print(n10)

[2 4 5 9 8 1]


In [50]:
n12 = n10.reshape(3,2)   # in n10 - 6 elements so 3 rows and 2 cols
print(n12)

[[2 4]
 [5 9]
 [8 1]]


In [51]:
n13 = n10.reshape(2,3)   # in n10 - 6 elements so 3 rows and 2 cols
print(n13)

[[2 4 5]
 [9 8 1]]


# Joining 2 arrays

In [52]:
n14 = np.arange(4)
print(n14)

[0 1 2 3]


In [54]:
n15 = np.arange(5,9)
print(n15)

[5 6 7 8]


In [56]:
n16 = np.concatenate((n14,n15))
print(n16)

[0 1 2 3 5 6 7 8]


# **Indexing and Slicing**

In [58]:
n17 = np.arange(10)
print(n17)

[0 1 2 3 4 5 6 7 8 9]


In [59]:
print(n17[n17>4])

[5 6 7 8 9]


In [60]:
print(n17[(n17>2) & (n17<8)])

[3 4 5 6 7]


In [61]:
fiveup = n17>5
print(fiveup)

[False False False False False False  True  True  True  True]


In [62]:
print(n17[fiveup])

[6 7 8 9]


Stack, Split

In [65]:
n18 =  np.array([[1,2],[3,4]])
n19 = np.array([[5,6],[7,8]])
np.hstack((n18,n19))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [66]:
np.vstack((n18,n19))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [67]:
n20 = np.arange(20)
print(n20)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [68]:
np.hsplit(n20,4)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

Copy

In [75]:
n21 = n20   #shallow copy
n20[0] = 30
print(n21)
print(n20)

[30 33  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[30 33  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [77]:
#deep  copy

n22 = n20.copy()
n20[1] = 34
print(n20)
print(n22)

[30 34  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[30 33  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Math Operations

In [78]:
n23 = np.array([2,3,4])
print(n23)

[2 3 4]


In [79]:
n24 = np.array([5,6,7])
print(n24)

[5 6 7]


In [83]:
print("Addition : " , n23+n24)
print("Subtraction: ", n23-n24)
print("Multiplication: ", n23*n24)

Addition :  [ 7  9 11]
Subtraction:  [-3 -3 -3]
Multiplication:  [10 18 28]


In [84]:
print(n23)

[2 3 4]


In [85]:
print(n23.sum())
print(n23.max())
print(n23.min())

9
4
2


In [86]:
print(n23*10)

[20 30 40]


# **Random Numbers**

In [87]:
np.random.rand(3,3)

array([[0.06665744, 0.90816738, 0.00157074],
       [0.58940904, 0.7712196 , 0.94837694],
       [0.88796891, 0.21698975, 0.71843048]])

In [89]:
np.random.randint(200, size=(4,2))

array([[ 56, 184],
       [ 81,  91],
       [ 16,  21],
       [  9,  15]])