In [3]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
list = [1,2,3,4,5]

In [6]:
np.array(list)

array([1, 2, 3, 4, 5])

In [7]:
mat  = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [8]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(2)

array([0.31852297, 0.75704669])

In [18]:
np.random.rand(5,5)

array([[0.17270628, 0.9120101 , 0.1254701 , 0.93988883, 0.56328292],
       [0.3386187 , 0.86567391, 0.24448152, 0.78299388, 0.2801961 ],
       [0.96381634, 0.49977862, 0.85841559, 0.05841369, 0.87792072],
       [0.09884055, 0.37007621, 0.09788903, 0.07410407, 0.58280575],
       [0.04931273, 0.32630929, 0.1730269 , 0.8208623 , 0.94941719]])

In [20]:
np.random.randint(1,100)

79

In [21]:
np.random.randint(1,100,10)

array([ 4, 65, 88, 45, 98, 32, 86, 77,  3, 37], dtype=int32)

In [23]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [44]:
a.shape

(20,)

In [45]:
a.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
b = np.array([3, 8, 1, 9, 2])
print(b)

[3 8 1 9 2]


In [38]:
print(b.min())

1


In [39]:
print(b.argmin())  # tells the position of the minimum element in the array

2


In [40]:
print(b.max())

9


In [41]:
print(b.argmax())

3


In [43]:
b.shape

(5,)

In [46]:
a.dtype

dtype('int64')

In [48]:
x = [0.2,0.4]


In [51]:
x = np.array(x)

In [52]:
x.dtype

dtype('float64')