# Import Numpy as np

In [2]:
import numpy as np

# Create an array of 10 zeros

In [3]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Create an array of 10 ones

In [5]:
b = np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


# Create an array of the integers from 10 to 50

In [9]:
c = np.arange(10,51)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


# Create an array of the even integers from 10 to 50

In [10]:
d = np.arange(10,51,2)
print(d)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


# Create a 3*3 matrix with values ranging from 0  to 8

In [11]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Create 3*3 identity matrix

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Use NumPy to generate a random number between 0 and 1

In [16]:
np.random.rand(1)

array([0.54047911])

# Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution

In [19]:
np.random.randn(25)

array([-0.83536162,  0.74449747, -0.1660033 , -0.79043611, -0.32862446,
        0.01184764, -0.13565172, -0.1700209 ,  0.62465022,  3.07119335,
       -0.20590278, -1.96967112, -0.4475849 , -0.04775366, -0.73512435,
        0.28277254, -1.10368291, -0.5293178 ,  0.11069798, -1.3814718 ,
       -0.46243556,  0.40254205,  1.14833296,  0.18304347,  1.68027398])

In [21]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# print the portion from 12-15, 17-20, 22-25

In [22]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

# print the element 20 in the matrix

In [24]:
print(mat[3,4])

20


# print 2,7,12

In [25]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

# print the last row

In [26]:
mat[4]

array([21, 22, 23, 24, 25])

# print last 2 row

In [29]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Get the sum of all the values in mat

In [31]:
print(mat.sum())

325


# Get the standard deviation of the values in mat

In [32]:
print(mat.std())

7.211102550927978


# Get the sum of all the columns in mat

In [33]:
mat.sum(axis=0) # columns

array([55, 60, 65, 70, 75])

In [35]:
mat.sum(axis=1) #rows

array([ 15,  40,  65,  90, 115])